import { z } from 'zod';

/*
 * Shared wire primitives. Every object schema in this package is a plain `z.object`, which strips
 * unknown keys on parse (ARCHITECTURE §4.4, §5.7). Game-specific payloads (actions, options,
 * views, events) are `z.unknown()` here and validated by each game's own schemas.
 */

/** Postgres row ids (users, rooms, matches) and client-generated UUIDv7 event ids. */
export const UuidSchema = z.uuid();
export const UserIdSchema = UuidSchema;
export const RoomIdSchema = UuidSchema;
export const MatchIdSchema = UuidSchema;
export const EventIdSchema = UuidSchema;

/** Catalog ids such as `cricket`, `lantern-quest` or `dev-tictactoe`. */
export const GameIdSchema = z
  .string()
  .regex(/^[a-z][a-z0-9-]{1,39}$/, 'Expected a lowercase kebab-case game id');

/** Mode ids such as `hand-cricket` or `classic`. */
export const ModeIdSchema = z
  .string()
  .regex(/^[a-z][a-z0-9-]{0,39}$/, 'Expected a lowercase kebab-case mode id');

/** The largest room has 8 seats (Quiz Battle). */
export const MAX_SEATS = 8;
export const SeatSchema = z
  .int()
  .min(0)
  .max(MAX_SEATS - 1);
export const SeatCountSchema = z.int().min(1).max(MAX_SEATS);
export const TeamSchema = z
  .int()
  .min(0)
  .max(MAX_SEATS - 1);

/**
 * Room and match versions. They encode `epoch × 2³² + n` (ARCHITECTURE §3.3), so they must stay
 * exact as JS numbers: non-negative safe integers (≤ 2⁵³ − 1).
 */
export const VersionSchema = z.int().min(0).max(Number.MAX_SAFE_INTEGER);

/** Wall-clock milliseconds since the Unix epoch (server time unless stated otherwise). */
export const WallTimeMsSchema = z.int().min(0).max(Number.MAX_SAFE_INTEGER);

/** A finite millisecond reading that may be fractional, e.g. `performance.now()`. */
export const ClockReadingSchema = z.number().min(0).max(Number.MAX_SAFE_INTEGER);

/** Idempotency key for `game:action`, generated by the client (a UUID or similar token). */
export const ClientActionIdSchema = z
  .string()
  .min(8)
  .max(64)
  .regex(/^[A-Za-z0-9_-]+$/, 'Expected a URL-safe token');

export const PLATFORMS = ['android', 'web'] as const;
export const PlatformSchema = z.enum(PLATFORMS);
export type Platform = z.infer<typeof PlatformSchema>;

/** UI languages that ship (en + ta). */
export const LOCALES = ['en', 'ta'] as const;
export const LocaleSchema = z.enum(LOCALES);
export type Locale = z.infer<typeof LocaleSchema>;

export const SHELVES = ['friends', 'adventure', 'relax'] as const;
export const ShelfSchema = z.enum(SHELVES);
export type Shelf = z.infer<typeof ShelfSchema>;

export const GAME_STATUSES = ['live', 'coming_soon', 'disabled', 'dev'] as const;
export const GameStatusSchema = z.enum(GAME_STATUSES);
export type GameStatus = z.infer<typeof GameStatusSchema>;

export const BOT_LEVELS = ['easy', 'medium', 'hard'] as const;
export const BotLevelSchema = z.enum(BOT_LEVELS);
export type BotLevel = z.infer<typeof BotLevelSchema>;

export const ROOM_PHASES = ['LOBBY', 'IN_PROGRESS', 'FINISHED', 'CLOSED'] as const;
export const RoomPhaseSchema = z.enum(ROOM_PHASES);
export type RoomPhase = z.infer<typeof RoomPhaseSchema>;

export const ROOM_ROLES = ['player', 'spectator'] as const;
export const RoomRoleSchema = z.enum(ROOM_ROLES);
export type RoomRole = z.infer<typeof RoomRoleSchema>;

/** App versions are plain semver (`1.4.2`, optionally with a pre-release tag). */
export const AppVersionSchema = z
  .string()
  .max(32)
  .regex(/^\d{1,4}\.\d{1,4}\.\d{1,6}(?:-[0-9A-Za-z.-]{1,16})?$/, 'Expected a semver version');

/** Expo runtime version (fingerprint hash or policy string) recorded per release. */
export const RuntimeVersionSchema = z.string().min(1).max(128);

/** Untrusted device label (ARCHITECTURE §7): never a credential. */
export const DeviceIdSchema = z
  .string()
  .min(1)
  .max(64)
  .regex(/^[A-Za-z0-9_.:-]+$/, 'Expected a device label token');

/** Display names: trimmed, 1–24 characters. The profanity filter runs on the server. */
export const DisplayNameSchema = z.string().trim().min(1).max(24);

/** Seed for the procedural avatar, generated on the client. */
export const AvatarSeedSchema = z.string().min(1).max(64);

/** The closed set of 8 reactions (OPEN_QUESTIONS C7). No free text in v1. */
export const REACTION_EMOJI = ['👏', '🔥', '😂', '😮', '😭', '🎉', '🙏', '😎'] as const;
export const ReactionEmojiSchema = z.enum(REACTION_EMOJI);
export type ReactionEmoji = z.infer<typeof ReactionEmojiSchema>;

/** Screaming-snake-case reason codes, closed per game (ARCHITECTURE §3.1). */
export const ReasonCodeSchema = z
  .string()
  .regex(/^[A-Z][A-Z0-9_]{0,47}$/, 'Expected a SCREAMING_SNAKE_CASE reason code');

/** A short public identity for seat cards, recent players and participants. */
export const PublicUserSchema = z.object({
  userId: UserIdSchema,
  name: DisplayNameSchema,
  avatarSeed: AvatarSeedSchema,
});
export type PublicUser = z.infer<typeof PublicUserSchema>;
