// The bundled offline practice pack (OQ D18): original English questions that never appear online.
// Starter bank: 10 per category. Every question is `needs_review` until fact-checked (OQ D32: a source
// URL checked with web access; 100% of Tamil Nadu and Indian Cinema, 20% of the rest). Facts are chosen
// not to go stale: no "current"/"latest", and no records or superlatives without an `asOf` year.

import type { Category, Difficulty, OptionIdx, QuizQuestion } from '../logic/rules';

export type QuestionStatus = 'approved' | 'needs_review';

export interface PackQuestion extends QuizQuestion {
  /** Where the fact can be verified. */
  source: string;
  /** Year the fact was true as of; required for records and superlatives (OQ D32). */
  asOf?: number;
  status: QuestionStatus;
  pack: 'online' | 'practice';
}

type Options = [string, string, string, string];

function q(
  id: string,
  category: Category,
  difficulty: Difficulty,
  prompt: string,
  options: Options,
  answerIdx: OptionIdx,
  source: string,
): PackQuestion {
  return {
    id,
    category,
    difficulty,
    prompt,
    options,
    answerIdx,
    source,
    status: 'needs_review',
    pack: 'practice',
  };
}

export const PRACTICE_PACK: readonly PackQuestion[] = [
  // ---------------------------------------------------------------- cricket
  q(
    'pr-cri-01',
    'cricket',
    1,
    'In cricket, how many legal deliveries make up a standard over?',
    ['4', '5', '6', '8'],
    2,
    'MCC Laws of Cricket, Law 17 (The over), lords.org/mcc/the-laws-of-cricket',
  ),
  q(
    'pr-cri-02',
    'cricket',
    1,
    "Which team won the first men's Cricket World Cup, held in England in 1975?",
    ['Australia', 'West Indies', 'England', 'India'],
    1,
    "ESPNcricinfo, Prudential World Cup 1975 final scorecard (Australia v West Indies, Lord's)",
  ),
  q(
    'pr-cri-03',
    'cricket',
    2,
    "At which ground did India win the 1983 men's Cricket World Cup final?",
    ["Lord's", 'Eden Gardens', 'The Oval', 'Old Trafford'],
    0,
    "ESPNcricinfo, 1983 World Cup final scorecard (India v West Indies, Lord's)",
  ),
  q(
    'pr-cri-04',
    'cricket',
    1,
    "Who captained India to the 1983 men's Cricket World Cup title?",
    ['Sunil Gavaskar', 'Mohinder Amarnath', 'Ravi Shastri', 'Kapil Dev'],
    3,
    "ESPNcricinfo, 1983 World Cup final scorecard; Britannica, 'Kapil Dev'",
  ),
  q(
    'pr-cri-05',
    'cricket',
    2,
    "In which year did India win the inaugural ICC Men's T20 World Cup?",
    ['2005', '2007', '2009', '2011'],
    1,
    'ICC, T20 World Cup 2007 final (India v Pakistan, Johannesburg), icc-cricket.com',
  ),
  q(
    'pr-cri-06',
    'cricket',
    1,
    'How long is a cricket pitch between the two sets of stumps?',
    ['18 yards', '20 yards', '22 yards', '24 yards'],
    2,
    'MCC Laws of Cricket, Law 6.1 (Area of pitch)',
  ),
  q(
    'pr-cri-07',
    'cricket',
    2,
    'Which Indian bowler took all 10 wickets in a Test innings against Pakistan in Delhi in 1999?',
    ['Harbhajan Singh', 'Anil Kumble', 'Javagal Srinath', 'Venkatesh Prasad'],
    1,
    'ESPNcricinfo, India v Pakistan 2nd Test, Delhi, February 1999 scorecard',
  ),
  q(
    'pr-cri-08',
    'cricket',
    2,
    "Who scored the first double century in men's One Day International cricket, in 2010?",
    ['Virender Sehwag', 'Rohit Sharma', 'Sachin Tendulkar', 'Chris Gayle'],
    2,
    'ESPNcricinfo, India v South Africa 2nd ODI, Gwalior, 24 February 2010 scorecard',
  ),
  q(
    'pr-cri-09',
    'cricket',
    1,
    "What is a batter's dismissal without scoring a run commonly called?",
    ['A maiden', 'A duck', 'A yorker', 'A bouncer'],
    1,
    'ESPNcricinfo cricket glossary ("duck")',
  ),
  q(
    'pr-cri-10',
    'cricket',
    2,
    'India played its first Test match in 1932. Who were the opponents?',
    ['Australia', 'South Africa', 'New Zealand', 'England'],
    3,
    "ESPNcricinfo, England v India only Test, Lord's, June 1932 scorecard",
  ),

  // ---------------------------------------------------------------- Indian cinema
  q(
    'pr-cin-01',
    'cinema',
    1,
    "Which 1913 film by Dadasaheb Phalke is regarded as India's first full-length feature film?",
    ['Alam Ara', 'Raja Harishchandra', 'Kisan Kanya', 'Devdas'],
    1,
    "Britannica, 'Dadasaheb Phalke'",
  ),
  q(
    'pr-cin-02',
    'cinema',
    2,
    "Which 1931 film was India's first sound feature film?",
    ['Alam Ara', 'Kalidas', 'Sant Tukaram', 'Ayodhyecha Raja'],
    0,
    "Britannica, 'Alam Ara'",
  ),
  q(
    'pr-cin-03',
    'cinema',
    1,
    'The Dadasaheb Phalke Award honours lifetime contribution to which field?',
    ['Literature', 'Classical music', 'Cinema', 'Sport'],
    2,
    'Directorate of Film Festivals, National Film Awards regulations (dff.gov.in)',
  ),
  q(
    'pr-cin-04',
    'cinema',
    2,
    "What was Satyajit Ray's first film as director, released in 1955?",
    ['Charulata', 'Jalsaghar', 'Nayak', 'Pather Panchali'],
    3,
    "Britannica, 'Satyajit Ray'",
  ),
  q(
    'pr-cin-05',
    'cinema',
    2,
    "Which 1957 Hindi film was India's first nominee for the Academy Award for Best Foreign Language Film?",
    ['Mother India', 'Pyaasa', 'Mughal-e-Azam', 'Do Bigha Zamin'],
    0,
    'Academy Awards database, 30th Academy Awards (1958), awardsdatabase.oscars.org',
  ),
  q(
    'pr-cin-06',
    'cinema',
    1,
    "The song 'Naatu Naatu', winner of the 2023 Academy Award for Best Original Song, is from which film?",
    ['Baahubali 2', 'Pushpa', 'RRR', 'Eega'],
    2,
    'Academy Awards database, 95th Academy Awards (2023)',
  ),
  q(
    'pr-cin-07',
    'cinema',
    1,
    "Who composed the music for Mani Ratnam's 1992 film 'Roja'?",
    ['Ilaiyaraaja', 'A. R. Rahman', 'M. S. Viswanathan', 'Harris Jayaraj'],
    1,
    "Britannica, 'A.R. Rahman'",
  ),
  q(
    'pr-cin-08',
    'cinema',
    1,
    'For which film did A. R. Rahman win two Academy Awards in 2009?',
    ['Lagaan', '127 Hours', 'Slumdog Millionaire', 'Roja'],
    2,
    'Academy Awards database, 81st Academy Awards (2009)',
  ),
  q(
    'pr-cin-09',
    'cinema',
    1,
    "In the 1975 film 'Sholay', which character did Amjad Khan play?",
    ['Jai', 'Veeru', 'Thakur Baldev Singh', 'Gabbar Singh'],
    3,
    "Britannica, 'Sholay'",
  ),
  q(
    'pr-cin-10',
    'cinema',
    1,
    "The 2001 film 'Lagaan' builds up to a match of which sport?",
    ['Cricket', 'Hockey', 'Football', 'Kabaddi'],
    0,
    "Academy Awards database, 74th Academy Awards nominee 'Lagaan'; BFI film entry 'Lagaan: Once upon a Time in India' (2001)",
  ),

  // ---------------------------------------------------------------- science
  q(
    'pr-sci-01',
    'science',
    1,
    'What is the chemical symbol for gold?',
    ['Ag', 'Au', 'Gd', 'Go'],
    1,
    'IUPAC Periodic Table of the Elements (iupac.org)',
  ),
  q(
    'pr-sci-02',
    'science',
    1,
    'Which planet is known as the Red Planet?',
    ['Venus', 'Jupiter', 'Mars', 'Mercury'],
    2,
    'NASA Science, Mars facts (science.nasa.gov/mars)',
  ),
  q(
    'pr-sci-03',
    'science',
    2,
    'Roughly how fast does light travel in a vacuum?',
    ['3,000 km/s', '30,000 km/s', '300,000 km/s', '3,000,000 km/s'],
    2,
    'BIPM SI Brochure: c = 299,792,458 m/s, exact by definition (bipm.org)',
  ),
  q(
    'pr-sci-04',
    'science',
    1,
    'Which gas do plants take in from the air for photosynthesis?',
    ['Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'],
    0,
    "Britannica, 'photosynthesis'",
  ),
  q(
    'pr-sci-05',
    'science',
    2,
    'How many chromosomes does a typical human body cell contain?',
    ['23', '46', '44', '48'],
    1,
    "NIH National Human Genome Research Institute, 'Chromosomes' fact sheet (genome.gov)",
  ),
  q(
    'pr-sci-06',
    'science',
    1,
    'Which Indian physicist won the 1930 Nobel Prize in Physics for his work on the scattering of light?',
    ['Homi J. Bhabha', 'Meghnad Saha', 'Satyendra Nath Bose', 'C. V. Raman'],
    3,
    'nobelprize.org, The Nobel Prize in Physics 1930',
  ),
  q(
    'pr-sci-07',
    'science',
    2,
    'What is the pH of pure water at 25 °C?',
    ['7', '0', '1', '14'],
    0,
    "Britannica, 'pH'",
  ),
  q(
    'pr-sci-08',
    'science',
    1,
    'Which organ produces the hormone insulin?',
    ['Liver', 'Pancreas', 'Kidney', 'Stomach'],
    1,
    "NIH NIDDK, 'Your Digestive System & How It Works' (niddk.nih.gov)",
  ),
  q(
    'pr-sci-09',
    'science',
    3,
    "In August 2023, India's Chandrayaan-3 lander touched down near which region of the Moon?",
    ['The north pole', 'The south pole', 'The far-side equator', 'The Sea of Tranquility'],
    1,
    'ISRO, Chandrayaan-3 mission page (isro.gov.in)',
  ),
  q(
    'pr-sci-10',
    'science',
    2,
    'What is the SI unit of electrical resistance?',
    ['Volt', 'Ampere', 'Watt', 'Ohm'],
    3,
    'BIPM SI Brochure, coherent derived units (bipm.org)',
  ),

  // ---------------------------------------------------------------- tech
  q(
    'pr-tec-01',
    'tech',
    1,
    "What does 'HTTP' stand for?",
    [
      'High Transfer Text Protocol',
      'Host Transfer Text Protocol',
      'HyperText Transfer Protocol',
      'HyperText Transmission Program',
    ],
    2,
    'IETF RFC 9110, HTTP Semantics (rfc-editor.org)',
  ),
  q(
    'pr-tec-02',
    'tech',
    1,
    'How many bits make up one byte?',
    ['4', '8', '10', '16'],
    1,
    "IEC 80000-13; Britannica, 'byte'",
  ),
  q(
    'pr-tec-03',
    'tech',
    1,
    'Who proposed the World Wide Web in 1989 while working at CERN?',
    ['Vint Cerf', 'Bill Gates', 'Tim Berners-Lee', 'Linus Torvalds'],
    2,
    "CERN, 'The birth of the Web' (home.cern)",
  ),
  q(
    'pr-tec-04',
    'tech',
    1,
    'Which programming language was created by Guido van Rossum?',
    ['Python', 'Java', 'Ruby', 'C'],
    0,
    "Python documentation, 'History and License' (docs.python.org)",
  ),
  q(
    'pr-tec-05',
    'tech',
    2,
    'In which year did Linus Torvalds first announce the Linux kernel?',
    ['1985', '1991', '1995', '2001'],
    1,
    "Torvalds' comp.os.minix announcement, 25 August 1991; Britannica, 'Linux'",
  ),
  q(
    'pr-tec-06',
    'tech',
    1,
    'In an email address such as name@example.com, which symbol separates the user name from the domain?',
    ['#', '&', '%', '@'],
    3,
    'IETF RFC 5322, Internet Message Format (addr-spec)',
  ),
  q(
    'pr-tec-07',
    'tech',
    1,
    'Hexadecimal is a number system with which base?',
    ['8', '10', '12', '16'],
    3,
    "Britannica, 'hexadecimal number system'",
  ),
  q(
    'pr-tec-08',
    'tech',
    1,
    'Which company bought Android Inc. in 2005 and went on to release the Android operating system?',
    ['Apple', 'Google', 'Microsoft', 'Nokia'],
    1,
    "Britannica, 'Android (operating system)'",
  ),
  q(
    'pr-tec-09',
    'tech',
    2,
    "India's Unified Payments Interface (UPI) was developed by which organisation?",
    ['NPCI', 'ISRO', 'SEBI', 'NASSCOM'],
    0,
    'National Payments Corporation of India, UPI product overview (npci.org.in)',
  ),
  q(
    'pr-tec-10',
    'tech',
    2,
    'What is the decimal number 5 written in binary?',
    ['100', '110', '101', '111'],
    2,
    "Arithmetic: 5 = 1×4 + 0×2 + 1×1; Britannica, 'binary number system'",
  ),

  // ---------------------------------------------------------------- general knowledge
  q(
    'pr-gen-01',
    'general',
    1,
    'What is the capital city of Australia?',
    ['Sydney', 'Canberra', 'Melbourne', 'Perth'],
    1,
    "Britannica, 'Canberra'; australia.gov.au",
  ),
  q(
    'pr-gen-02',
    'general',
    1,
    'How many days are there in a leap year?',
    ['364', '365', '366', '367'],
    2,
    "Britannica, 'leap year'",
  ),
  q(
    'pr-gen-03',
    'general',
    1,
    "What is India's national animal?",
    ['Lion', 'Elephant', 'Indian rhinoceros', 'Tiger'],
    3,
    'Know India, National Symbols (knowindia.india.gov.in)',
  ),
  q(
    'pr-gen-04',
    'general',
    1,
    "Who wrote 'Jana Gana Mana', India's national anthem?",
    ['Bankim Chandra Chattopadhyay', 'Rabindranath Tagore', 'Subramania Bharati', 'Sarojini Naidu'],
    1,
    'Know India, National Symbols: National Anthem (knowindia.india.gov.in)',
  ),
  q(
    'pr-gen-05',
    'general',
    1,
    'In which year did the Constitution of India come into force, making India a republic?',
    ['1947', '1949', '1950', '1952'],
    2,
    'Constitution of India (legislative.gov.in); Know India, Republic Day',
  ),
  q(
    'pr-gen-06',
    'general',
    1,
    'The Great Barrier Reef lies off the coast of which country?',
    ['Australia', 'Indonesia', 'Philippines', 'Brazil'],
    0,
    'UNESCO World Heritage List, Great Barrier Reef (whc.unesco.org)',
  ),
  q(
    'pr-gen-07',
    'general',
    1,
    'Which monument in Agra did Shah Jahan commission in memory of Mumtaz Mahal?',
    ['Red Fort', 'Qutub Minar', 'Taj Mahal', 'Charminar'],
    2,
    'UNESCO World Heritage List, Taj Mahal (whc.unesco.org)',
  ),
  q(
    'pr-gen-08',
    'general',
    2,
    'Mount Everest lies on the border between Nepal and which other country?',
    ['India', 'Bhutan', 'Pakistan', 'China'],
    3,
    "Britannica, 'Mount Everest'",
  ),
  q(
    'pr-gen-09',
    'general',
    1,
    'Who was the first person to walk on the Moon, in July 1969?',
    ['Buzz Aldrin', 'Neil Armstrong', 'Yuri Gagarin', 'Michael Collins'],
    1,
    'NASA, Apollo 11 mission overview (nasa.gov)',
  ),
  q(
    'pr-gen-10',
    'general',
    2,
    "Mahatma Gandhi's 1930 Salt March ended at which coastal village in Gujarat?",
    ['Dandi', 'Porbandar', 'Sabarmati', 'Dwarka'],
    0,
    "Britannica, 'Salt March'",
  ),

  // ---------------------------------------------------------------- Tamil Nadu
  q(
    'pr-tn-01',
    'tamil-nadu',
    1,
    'What is the capital of Tamil Nadu?',
    ['Madurai', 'Coimbatore', 'Chennai', 'Tiruchirappalli'],
    2,
    'Government of Tamil Nadu (tn.gov.in)',
  ),
  q(
    'pr-tn-02',
    'tamil-nadu',
    1,
    "In which city is the Brihadisvara Temple, part of UNESCO's 'Great Living Chola Temples'?",
    ['Thanjavur', 'Madurai', 'Kanchipuram', 'Rameswaram'],
    0,
    'UNESCO World Heritage List, Great Living Chola Temples (whc.unesco.org)',
  ),
  q(
    'pr-tn-03',
    'tamil-nadu',
    2,
    'Which Chola king built the Brihadisvara Temple at Thanjavur?',
    ['Rajendra Chola I', 'Karikala Chola', 'Rajaraja Chola I', 'Kulothunga Chola I'],
    2,
    'UNESCO World Heritage List, Great Living Chola Temples (whc.unesco.org)',
  ),
  q(
    'pr-tn-04',
    'tamil-nadu',
    2,
    'The Shore Temple at Mamallapuram was built under which dynasty?',
    ['Chola', 'Pallava', 'Pandya', 'Chera'],
    1,
    'UNESCO World Heritage List, Group of Monuments at Mahabalipuram (whc.unesco.org)',
  ),
  q(
    'pr-tn-05',
    'tamil-nadu',
    1,
    'Who wrote the Thirukkural?',
    ['Kambar', 'Ilango Adigal', 'Avvaiyar', 'Thiruvalluvar'],
    3,
    "Britannica, 'Tirukkural'",
  ),
  q(
    'pr-tn-06',
    'tamil-nadu',
    2,
    'How many couplets does the Thirukkural contain?',
    ['1,000', '1,080', '1,330', '1,500'],
    2,
    "Britannica, 'Tirukkural' (133 chapters of 10 couplets)",
  ),
  q(
    'pr-tn-07',
    'tamil-nadu',
    1,
    'Which classical dance form originated in Tamil Nadu?',
    ['Bharatanatyam', 'Kathakali', 'Kuchipudi', 'Odissi'],
    0,
    "Britannica, 'bharata natyam'; Sangeet Natak Akademi, classical dance forms",
  ),
  q(
    'pr-tn-08',
    'tamil-nadu',
    2,
    'The main day of the Pongal harvest festival falls on the first day of which Tamil month?',
    ['Chithirai', 'Aadi', 'Karthigai', 'Thai'],
    3,
    "Britannica, 'Pongal'; Government of Tamil Nadu public holiday list",
  ),
  q(
    'pr-tn-09',
    'tamil-nadu',
    3,
    "'The Elephant Whisperers', winner of the 2023 Academy Award for Best Documentary Short Film, is set in which tiger reserve?",
    ['Mudumalai', 'Anamalai', 'Sathyamangalam', 'Kalakad Mundanthurai'],
    0,
    'Academy Awards database, 95th Academy Awards (2023); Tamil Nadu Forest Department, Theppakadu Elephant Camp, Mudumalai Tiger Reserve',
  ),
  q(
    'pr-tn-10',
    'tamil-nadu',
    1,
    'The Meenakshi Amman Temple stands in which city?',
    ['Thanjavur', 'Madurai', 'Tiruchirappalli', 'Kanchipuram'],
    1,
    "Britannica, 'Madurai'; Tamil Nadu Tourism (tamilnadutourism.tn.gov.in)",
  ),
];
